dev:
  MONGODB_URI: ${env:MONGODB_URI}
  JWT_ACCESS_SECRET: ${env:JWT_SECRET}
  CLIENT_URL: ${env:FRONTEND_URL}
  JWT_REFRESH_SECRET: ${env:REFRESH_TOKEN_SECRET}
  OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}

prod:
  MONGODB_URI: ${env:MONGODB_URI}
  JWT_ACCESS_SECRET: ${env:JWT_SECRET}
  CLIENT_URL: ${env:FRONTEND_URL}
  JWT_REFRESH_SECRET: ${env:REFRESH_TOKEN_SECRET}
  OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
