export const defaultSettings = {
  fontFamily: "Arial",
  fontSize: "medium",
  colorScheme: {
    primaryColor: "#000000",
    secondaryColor: "#666666",
    textColor: "#333333",
  },
  layout: "modern",
  activeSection: {
    jobIndustry: true,
    personalInfo: true,
    professionalSummary: true,
    workExperience: true,
    education: true,
    socialLinks: true,
    projects: false,
    languages: true,
    selectedSkills: true,
    certificate: false,
    awards: false,
    openSourceContributions: false,
    customSections: false,
  },
  margin: "normal",
  lineHeight: "normal",
  sectionSpacing: "normal",
};
